### ISSUE TITLE
"Table 'observium.links' doesn't exist"

### ISSUE THREAD

**Issue by lan31** [mathieupoussin/observium_map_generator#1]
# python /opt/observium/graph.py CHANGEME

Generating graph : Traceback (most recent call last):
  File "/opt/observium/graph.py", line 189, in <module>
    graph = discover_links(graph, this_device)
  File "/opt/observium/graph.py", line 143, in discover_links
    cursor.execute(query_template, this_device)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1146, "Table 'observium.links' doesn't exist")

**Comment by sysblade** [comment]
The tables probably have changed since I made this script :)

I have a community setup that I could check in a few days, but feel free to pull request if you have something already done on your side.

**Comment by mntuyi** [comment]
Is someone had time to get this resolved? I didn't find a new version since 2015

**Comment by sysblade** [comment]
I think you should try to give a try on the official IRC chan https://docs.observium.org/community/

I've been contacted once as someone wanted to integrate it in Observium or try to adapt it for the new versions, I don't know if this has been done at the end.

Unfortunately I don't have any Observium setup to work on that anymore.

**Comment by athompso** [comment]
The `links` table has been renamed `neighbors`:

```update/216.sql:RENAME TABLE `links` TO `neighbours`;```

That's a trivial fix.  However, that's not the only problem, they've also removed the `ports-state` table altogether:

```update/341.sql:DROP TABLE `ports-state`;```

and I don't know if anything replaced it... working on that.  The SVN log message is equally unhelpful to me:

```
[root@observium update]# svn log 341.sql  
------------------------------------------------------------------------
r8564 | adama | 2017-05-26 05:24:31 -0500 (Fri, 26 May 2017) | 2 lines

[MERGE] Stable merge of 8546 to r8563

------------------------------------------------------------------------
r8556 | adama | 2017-05-22 14:39:59 -0500 (Mon, 22 May 2017) | 2 lines

[IMPROVE] Remove bgpPeers-state and bgpPeers_cbgp-state.

------------------------------------------------------------------------
```

(NOTE: Those filenames and SVN log are from the subscription version, not community.)

**Comment by Faabvk** [comment]
Would be fixed in PR #3 if accepted.
