### ISSUE TITLE
Please  ^ help.  observium version  Observium CE 18.9.9420

### ISSUE THREAD

**Issue by roysbike** [mathieupoussin/observium_map_generator#2]
# python /opt/observium/graph.py CHANGEME

```
Generating graph : Traceback (most recent call last):
  File "/opt/observium/graph.py", line 189, in <module>
    graph = discover_links(graph, this_device)
  File "/opt/observium/graph.py", line 143, in discover_links
    cursor.execute(query_template, this_device)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 240, in execute
    self.errorhandler(self, ProgrammingError, str(m))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 52, in defaulterrorhandler
    raise errorclass(errorvalue)
_mysql_exceptions.ProgrammingError: not all arguments converted during string formatting

```

**Comment by LucasGitDev** [comment]
@roysbike Fixed?

**Comment by sysblade** [comment]
Hello, 
sorry I don’t have any observium setup I can use to fix it, but feel free to do a PR if you find a way to fix it :)
Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicodier** [comment]
Just added a PR to make this work with the latest Observium version.  @roysbike @LucasGitDev @kedare 
Got it working for a big network with 200+ devices.
